version: '3'
services:
  jenkins:
    build: ./docker/jenkins_master/
    networks:
      - jenkins
    ports:
      - '8080:8080'
      - '9080:9080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
      - JENKINS_USER="admin"
      - JENKINS_PASS="admin"
  jenkins_slave:
    build: ./docker/jenkins_slave/
  jenkins_job:
    build: ./docker/jenkins_job/
    networks:
      - jenkins
    depends_on:
      - jenkins
    command: sh -c 'dockerize -wait http://jenkins:8080 -timeout 180s -wait-retry-interval 5s && /entrypoint.sh jenkins:8080'
  local_build_test:
    build: .
    command: sh -c "cd build/ && cmake .. && make && ./test/cool_game_test"
  local_build_run:
    build: .
    command: sh -c "cd build/ && cmake .. && make && ./src/cool_game"
networks:
  jenkins:
volumes:
  jenkins_data:
